language: python
dist: xenial
matrix:
    include:
        -   env: TOXENV=py35
            python: 3.5
        -   env: TOXENV=py36
            python: 3.6
        -   env: TOXENV=py37
            python: 3.7
install: pip install coveralls tox
script: tox
after_success: coveralls
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/pre-commit
notifications:
  email: false
